// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiqvezuinxvitauapbvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcXZlenVpbnh2aXRhdWFwYnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTcyMTMsImV4cCI6MjA2MDI5MzIxM30.Pw2I9ya2kDsNIMd1p34wxpYu3X7wyHcnGxCi9Wge8KE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);